owner: EnsembleTravelGroup
repo: EnsembleTravelUpptime
user-agent: topherjenkins87
sites:
  - name: EnsembleTravel.com
    url: https://www.ensembletravel.com
  - name: Atlas
    url: https://agent.ensembletravel.com
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - topherjenkins87
  - toddhutzulak
status-website:
  logoUrl: https://agent.ensembletravel.com/img/logo/etg/floret-rev.png
  name: "Ensemble Travel Group - Status Page"
  introTitle: "**Ensemble Travel Group** web services status monitoring."
  introMessage: "The ETG status page uses **real-time** data to monitor our web services."
  cname: status.ensembletravel.com
